<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>LittleVillage.Core</RootNamespace>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\ink\ink-engine-runtime\ink-engine-runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LittleVillage.Core.Tests" />
  </ItemGroup>

</Project>
